### ISSUE TITLE
supplement code

### ISSUE THREAD

**Issue by wangp-blog** [Kobaayyy/Awesome-ICCV2021-Low-Level-Vision#2]
The paper 'Attention-based Multi-Reference Learning for Image Super-Resolution'
It's code could be found in the Abstract.

https://marcopesavento.github.io/AMRSR/ 
ps：coming soon
![image](https://user-images.githubusercontent.com/31883473/148320136-cb15ab6e-07ac-4356-a454-f46303cb26bf.png)

**Comment by Kobaayyy** [comment]
> The paper 'Attention-based Multi-Reference Learning for Image Super-Resolution' It's code could be found in the Abstract.
> 
> https://marcopesavento.github.io/AMRSR/ ps：coming soon ![image](https://user-images.githubusercontent.com/31883473/148320136-cb15ab6e-07ac-4356-a454-f46303cb26bf.png)

ok thx, I've modified it.
